# Setup
title:      dischord.org
tagline:    If credit's what matters, I'll take credit
url:        http://dischord.org
baseurl:    /
permalink:  /:year/:month/:day/:title

github_username: yankcrime
twitter_username: yankcrime
google_analytics: 'UA-61084998-1'
flickr:
    api_key: 167cb17dcb886af997217243c8a6d1a3

# Google analytics
google_analytics: 'UA-61084998-1'

# About/contact
author:
  name:              Nick Jones
  url:               https://twitter.com/yankcrime
  email:             nick@dischord.org

# Dependencies
markdown:            redcarpet
highlighter:         pygments
