# Setup
title:      dischord.org
tagline:    If credit's what matters, I'll take credit
url:        http://dischord.org
baseurl:    /
permalink:  /:year/:month/:day/:title/

github_username: yankcrime
twitter_username: yankcrime
flickr:
    api_key: 

# About/contact
author:
  name:              Nick Jones
  url:               https://twitter.com/yankcrime
  email:             nick@dischord.org

# Dependencies
markdown:            kramdown
highlighter:         pygments

plugins:
  - kramdown
  - jekyll-gist
  - pygments.rb
  - jekyll-redirect-from
