source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-gist'
gem 'jekyll-redirect-from'
gem 'nokogiri'
gem 'typhoeus'
gem 'kramdown'
gem 'redcarpet'
gem 'pygments.rb'
gem 'ethon'
gem 'multipart-post'
gem 'ruby_dep'
